esphome:
  name: ovoeasy
  name_add_mac_suffix: true
  friendly_name: "OvoEasy Incubator"
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 16MB

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_FATFS_LFN_HEAP: y
      CONFIG_FATFS_MAX_LFN: "255"
  flash_size: 16MB

psram:
  mode: quad
  speed: 80MHz

logger:
  level: INFO
  baud_rate: 115200

api:
  encryption:
    key: !secret ha_api_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    entity_category: diagnostic
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP32 Temperature"
    id: esp32_temp
    entity_category: diagnostic
    update_interval: 60s
