# Rotary encoder and pushbuttons

sensor:
  - platform: rotary_encoder
    name: "Encoder"
    id: rotary_encoder_sensor
    pin_a:
      number: GPIO41
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO40
      mode: INPUT_PULLUP
    resolution: 1
    publish_initial_value: true
    restore_mode: ALWAYS_ZERO

binary_sensor:
  - platform: gpio
    name: "Encoder Button"
    id: encoder_button
    pin:
      number: GPIO42
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    name: "Button A"
    id: button_a
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    name: "Button B"
    id: button_b
    pin:
      number: GPIO45
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    name: "Button C"
    id: button_c
    pin:
      number: GPIO46
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
